--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered

        - DeviceCommunication
        - SwitchingSystemQTC
        - Resources

    Aliases:
      HVSwitching: BrandBox
      LVSwitching: Keithley 708B Switching

    Devices:
        Keithley_Matrix:
            Device_name: Keithley 708B Switching
            Connection_resource: IP:TCPIP0::192.168.130.199::inst0::INSTR
            Device_IDN: KEITHLEY INSTRUMENTS INC.,MODEL 708B,04402824,01.04c
            Cards: 1 # Device specific variable used to determine how many cards are inserted

        BrandBox:
          Device_name: BrandBox
          Connection_resource: RS232:5
          Device_IDN: HV-Relay Controller V1.6/18.Apr.2019
  
