--- # Dummy config file for testing

  Filetype: ASCII # Other options are json

  #Output: C:\Users\dbloech\Desktop\QTC_Plots\VPX28442\IVCV #Output basename of the plots

  #Save_as: # Possible options: html, (svg), png, pdf -> Only works if wkhtmltopdf is installed and html plot is generated,
    #- html
    #- png
    #- svg
    #- pdf # does not work correctly

  Analysis:
    - IVCV_QTC # The type of analysis, which will be performed

  #Poolsize: 4 # Maximum pool size of simultaneous analysis scripts

# Optional Parameters
  ASCII_file_specs: # The specifications for the ascii file type measurements files
    header_lines: 8
    measurement_description: 9
    units_line: 9
    data_start: 10

  # Options for the different Analyses scripts
  # These options are entirely up to you and what you need in your analysis
  IVCV_QTC:
      General: # Options common to all plots
          fontsize: {'title': 28, 'labels': 24, 'xticks': 24, 'yticks': 24, 'legend': 11}
          responsive: False
          width: 1200
          height: 700
          shared_axes: False
      Layout:
          cols: 1 # How many columns there are, these must the the names of the methods!!! and a valid parameter

      DoSpecialPlots: # Whether or not to do the SpecialPlot, it may not succeed if not at least one measuremnt has this special plot stated
          - BoxWhisker

      BoxWhiskerOptions:
          shared_axes: False
          box_alpha: 0.3
          width: 2600
          height: 1500

      temperature:
          PlotLabel: Temperature
          AdditionalPlots:
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: False
              #xlabel: Pad [#]
              #ylabel: Temperature [deg]

      humidity:
          PlotLabel: Humidity
          AdditionalPlots:
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: False
              #xlabel: Pad [#]
              #ylabel: Humidity [rel%]

      current:
          PlotLabel: IV CURVES
          UnitConversion: nano
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              logy: True
              logx: False
              invert_xaxis: False
              invert_yaxis: false
              #ylim: !!python/tuple [0, 10e-6]
              #xlim: !!python/tuple [0, 1000]
              legend_position: "bottom_right"
              #aspect: equal
              padding: !!python/tuple [0, 0.1]
              show_grid: True
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              #xlabel: voltage [V]
              #ylabel: current [A]
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation


      capacitance:
          PlotLabel: CV CURVES
          UnitConversion: nano
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              logy: False
              logx: False
              invert_xaxis: False
              invert_yaxis: False
              #ylim: !!python/tuple [0, 10e-6]
              #xlim: !!python/tuple [0, 1000]
              legend_position: "bottom_right"
              #aspect: equal
              padding: !!python/tuple [0, 0.1]
              show_grid: True
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              #xlabel: voltage [V]
              #ylabel: capacitance [F]
              shared_axes: False

      1C2:
          PlotLabel: CV CURVES - Full depletion
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              logy: False
              logx: False
              invert_xaxis: False
              invert_yaxis: False
              #ylim: !!python/tuple [0, 10e-6]
              #xlim: !!python/tuple [0, 1000]
              #legend_position: "bottom_right"
              #aspect: equal
              padding: !!python/tuple [0, 0.1]
              show_grid: True
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              #xlabel: voltage [V]
              ylabel: 1/c^2 [arb. units]
              shared_axes: False
              ylim: !!python/tuple [0, 0.08]
              #xlim: !!python/tuple [0, 500]
