--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)


    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered
        - DataVisualization
        - CombiningPlots
        - Documentation
        - StripAnalysis
        - DataBrowser
        
    xml_template: CMSxmlTemplate
    override_data: true # If data was changed during an analyis this supresses the prompt which data you want to use. And either overrides it automatically or not


