{   "set_umotgrad": "setumotgrad", 
    "calibrate_motor": [
        "calibrate", 
        "rm"
    ], 
    "abort_movement": "Ctrl C", 
    "set_acceleration": "setaccel", 
    "error_query": "geterror", 
    "table_zmax": "11100.0", 
    "Device_name": "ITK Corvus", 
    "default_joy_speed": "10000.0", 
    "command_order": "-1", 
    "get_speed": "getvel", 
    "current_speed": 10000.0, 
    "table_ymax": "193000.0", 
    "default_joysticktype": "3", 
    "get_pos_from_init": "devpos", 
    "set_axis": "setaxis", 
    "default_acceleration": "3000.0", 
    "default_pitch": [
        "1.0 1", 
        "1.0 2", 
        "1.0 3", 
        "1.0 0"
    ], 
    "default_dimension": "3", 
    "set_units": "setunit", 
    "set_mode": "mode", 
    "set_axis_scale": "scale", 
    "get_acceleration": "getaccel", 
    "default_speed": "10000.0", 
    "default_motiondir": [
        "1 1", 
        "1 2", 
        "0 3"
    ], 
    "default_mode": "0", 
    "table_xmin": "0.0", 
    "Device_type": "Motor control", 
    "default_joystick": "0", 
    "set_joy_speed": "setjoyspeed", 
    "set_umotmin": "setumotmin", 
    "default_axis_scale": "1.0 1.0 1.0", 
    "default_umotgrad": [
        "55 1", 
        "55 2", 
        "55 3"
    ], 
    "set_dimension": "setdim", 
    "table_ymin": "0.0", 
    "imp:default_units": [
        "1 1", 
        "1 2", 
        "1 3", 
        "1 0"
    ], 
    "set_speed": "setvel", 
    "table_xmax": "97300.0", 
    "set_move_to": "move",
    "CSV_move_to": "x,y,z",
    "selftest": "selftest", 
    "Connection_type": "RS232:1", 
    "all_done": "status", 
    "get_axis": "getaxis", 
    "set_motiondir": "setmotiondir", 
    "set_relative_move_to": "rmove",
    "CSV_relative_move_to": "x,y,z",
    "Baud_rate": "9600", 
    "reset_device": ["restore", "ico", "clear"],
    "get_position": "pos", 
    "default_axis": ["1 1", "1 2", "1 3"], 
    "separator": " ",
    "Device_IDN": "Corvus 1 462 1 0", 
    "set_pitch": "setpitch", 
    "set_joystick": "joystick", 
    "table_zmin": "0.0", 
    "set_joysticktype": "setjoysticktype", 
    "Display_name": "Corvus", 
    "default_umotmin": ["1850 1", "1850 2", "1850 3"], 
    "device_IDN_query": "identify", 
    "default_polepairs": ["50 1", "50 2", "50 3"], 
    "set_polepairs": "setpolepairs",
    "execution_terminator": ""
}