{
    "default_current_NPLC": "10", 
    "default_lower_auto_range": "2E-9", 
    "read_current": "MEAS:CURR?", 
    "Device_name": "6517B Keithley Elektrometer", 
    "set_resistance_range": "RES:RANG ", 
    "set_current_range": "CURR:RANG", 
    "imp:default_auto_current_range": "ON", 
    "set_measure_current": "SENS:FUNC 'CURR'", 
    "imp:default_zero_check": "ON", 
    "set_auto_current_range": "CURR:RANG:AUTO", 
    "Read": "READ?", 
    "set_upper_auto_range": "CURR:RANG:AUTO:ULIM", 
    "set_measure_charge": "SENS:FUNC 'CHAR'", 
    "read_voltage": "MEAS:VOLT?", 
    "set_voltage_range": "VOLT:RANG ", 
    "Device_type": "Elektrometer", 
    "set_measure_voltage": "SENS:FUNC 'VOLT'", 
    "default_upper_auto_range": "200E-6", 
    "Connection_type": "GPIB:15", 
    "Display_name": "ELMETER", 
    "set_measure_resistance": "SENS:FUNC 'RES'", 
    "set_guard": "VOLT:GUARD ", 
    "set_zero_correlation": "SYST:ZCOR", 
    "set_lower_auto_range": "CURR:RANG:AUTO:LLIM", 
    "Baud_rate": 57600, 
    "trigger_reading": "INIT", 
    "set_voltage": "SOUR:VOLT:LEV ", 
    "read_charge": "MEAS:CHAR?", 
    "set_acquire_zero_correlation": "SYST:ZCOR:ACQ", 
    "set_current_NPLC": "CURR:NPLC", 
    "Device_IDN": "KEITHLEY INSTRUMENTS INC.,MODEL 6514,4022702,A13   Aug 30 2011 15:09:19/A02  /E", 
    "default_current_range": "2E-9", 
    "set_zero_check": "SYST:ZCH", 
    "read_resitance": "MEAS:RES?", 
    "set_output": "OUTP ", 
    "set_only_value_read": "FORM:ELEM READ"
}