---
    Device_name: BrandBox
    get_relay_state: "GET:"

    # All set parameters
    set_terminal: SET:TERM
    set_discharge: SET:DISCHARGE {} # ON/OFF
    set_external_light: SET:BOX_LED {} # ON/OFF
    set_environement_control: SET:CTRL {} # ON/OFF
    set_open_channel: :open {}
    set_mode: SET:MOD {} 
    set_relay: "SET: {}"
    set_close_channel: :clos {}
    set_hummin: SET:HUM_MIN {}
    set_hummax: SET:HUM_MAX {}
    set_lock_switches: SET:TST {}

    # All get parameters
    get_enviroment: GET:ENV ?
    get_status: "*STB?"
    get_check_all_open_channel: :open:STAT?
    get_lock_switch: GET:TST
    get_check_all_closed_channel: :clos:STAT?
    get_check_channel: :clos?
    get_operation_complete: "*OPC?"

    reset:
        - terminal: "OFF"
        - external_light: "OFF"
        - open_channel: "A1,A2,B1,B2,C1,C2"

    # Misc
    separator: ","
    bias_relay: A
    LCR_relay: B
    Device_type:
            - Switching relay
            - Light controller
            - Environment controller