{
    "Connection_type": "RS232:15", 
    "get_relay_state": "GET:", 
    "Display_name": "Brand Box", 
    "enviroment_query": "GET:ENV ?", 
    "bias_relay": "A", 
    "set_discharge": "SET:DISCHARGE", 
    "set_external_light": "SET:BOX_LED", 
    "Device_name": "HV_box", 
    "set_environement_control": "SET:CTRL", 
    "get_status": "*STB?", 
    "Device_IDN": "HV-Relay Controller V1.5/09.Oct.2018",
    "check_all_open_channel": ":open:STAT?", 
    "set_open_channel": ":open",
    "CSV_open_channel": "channel",
    "CSV_close_channel": "channel",
    "default_external_light": "OFF", 
    "default_open_channel": "A1,A2,B1,B2,C1,C2", 
    "set_close_channel": ":clos", 
    "get_lock_switch": "GET:TST", 
    "set_mode": "SET:MOD", 
    "set_relay": "SET:", 
    "check_all_closed_channel": ":clos:STAT?", 
    "check_channel": ":clos?", 
    "LCR_relay": "B", 
    "Device_type": [
        "Switching relay", 
        "Light controller", 
        "Environment controller"
    ], 
    "lock_switches": "SET:TST", 
    "operation_complete": "*OPC?",
    "separator": ",",
    "set_hummin": "SET:HUM_MIN",
    "set_hummax": "SET:HUM_MAX"
}