---
    Device_name: Keithley 708B Switching
    Device_type: Switching relay 
    
    # Set
    set_open_channel: channel.open({})
    set_exclusive_close_channel: channel.exclusiveclose("{}")
    set_close_channel: channel.close("{}")
    set_open_channel_all:  channel.open("allslots")
    set_close_channel_all:  channel.close("allslots")
    set_beeper: beeper.enable = {}
    set_clear_forbidden_channels: channel.clearforbidden({})
    set_forbidden_channels: channel.setforbidden({})
    set_connect_rule: channel.connectrule = {}
    set_connect_sequential: channel.connectsequential = {}
    set_reset_channels: channel.reset({})
    set_lockout: display.locallockout = {}
    
    
    # Get
    get_forbidden_channels: print(channel.getforbidden("allslots"))
    get_closed_channels: print(channel.getclose("allslots"))
    get_close_count: print(channel.getcount({}))
    get_delay: print(channel.getdelay({}))
    get_channel_state: print(channel.getstate("allslots"))
    get_errorqueue_count: print(errorqueue.count)
    get_error: print(errorqueue.next())
    get_operation_complete:
            command: opc() waitcomplete() print("1")
            success: 1
            type: str

    # Warning: TSPlink reset only works if another device with a unique tsp node number is present in the system
    reset_device: [reset(), errorqueue.clear()]
    reset:
        - reset_channels: "'allslots'"
        - beeper: beeper.OFF
        - connect_rule: channel.BREAK_BEFORE_MAKE
        - connect_sequential: channel.OFF
        - lockout: display.UNLOCK

    # Misc
    separator: ";"
    beep: beeper.beep({},{})
    stop_script: exit()
    wait_complete: waitcomplete()
    reset_tsplink: tsplink.reset()
    Rows: [A,B,C,D,E,F,G,H]
    Columns: [01,02,03,04,05,06,07,08,09,10,11,12]
    device_exclusive_switching: True # If this is on true all switching logic will be done via the device. Make sure you configured the device correctly
    
