{
    "Connection_type": "GPIB:19", 
    "default_integration_time": "LONG", 
    "set_voltage": ":VOLT", 
    "default_voltage": "1.", 
    "Device_name": "Agilent E4980A", 
    "default_correction_state": "OFF", 
    "set_output_format": ":FORM:DATA", 
    "all_done": "*OPC?", 
    "default_measurement_type": "CPRP", 
    "set_cable_length": ":CORR:LENG", 
    "set_measurement_type": ":FUNC:IMP", 
    "set_correction_state": ":CORR:LOAD:STAT", 
    "set_perform_open_correction": ":CORR:OPEN:EXE", 
    "set_apply_short_correction": ":CORR:SHORT:STAT", 
    "set_correction_type": ":CORR:LOAD:TYPE", 
    "Device_IDN": "Agilent Technologies,E4980A,MY46208270,A.06.15", 
    "Read": ":FETC?", 
    "default_frequency": "1000", 
    "set_clear_display": "DISP:CCL", 
    "set_frequency": ":FREQ", 
    "default_output_format": "ASC", 
    "default_correction_type": ":CPRP", 
    "default_cable_length": "4", 
    "Device_type": "LCRmeter", 
    "set_integration_time": ":APER", 
    "Display_name": "LCR", 
    "set_perform_short_correction": ":CORR:SHORT:EXE", 
    "set_apply_open_correction": ":CORR:OPEN:STAT"
}