---
    Device_name: Keithley Switching Matrix
    Device_type: Switching relay 
    
    # Set
    set_open_channel: :open (@{channel})
    set_close_channel: :clos (@{channel})
    
    
    # Get
    get_check_channel: :clos? 
    get_check_all_closed_channel: :clos:STAT?
    get_operation_complete: "*OPC?"   


    reset:
        - open_channel: all 

    # Misc
    separator: ","
