--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered

        - DeviceCommunication
        - Switching
        - Resources

    #Devices:
    #    Matrix:
    #        Device_name: Keithley 708B Switching
    #        Connection_type: IP:TCPIP0::dyn-130-036.local.hephy.at::inst0::INSTR
    #        Device_IDN: KEITHLEY INSTRUMENTS INC.,MODEL 708B,04402824,01.04c
  
