---
    Settings_name: Switching
    Idiel:
        HVSwitching: # Name of the device or a alias (if defined) which is defined in the settings
            - A1
            - B1
            - C2
         
        LVSwitching: # Name of the device or a alias (if defined) which is defined in the settings
            - 2!3!3
            - 2!4!4
        
     
    Cback: 
        HVSwitching: 
            - A1
            - B1
            - C2
         
        LVSwitching: 
            - 2!4!1
        
     
    Rint: 
        HVSwitching: 
            - A1
            - B1
            - C1
         
        LVSwitching: 
            - 2!4!5
            - 2!2!3

    Rpoly: 
        HVSwitching: 
            - A1
            - B1
            - C1
         
        LVSwitching: 
            - 2!4!3
        
     
    IV: 
        HVSwitching: 
            - A1
            - B1
            - C2
         
        LVSwitching: 
     
    CintAC: 
        HVSwitching: 
            - A1
            - B1
            - C1
         
        LVSwitching: 
            - 2!1!1
            - 2!3!2
        
     
    Istrip: 
        HVSwitching: 
            - A1
            - B1
            - C2
         
        LVSwitching: 
            - 2!4!5
        
     
    Cac: 
        HVSwitching: 
            - A1
            - B1
            - C2
         
        LVSwitching: 
            - 2!4!1
            - 2!3!2
        
     
    Cint: 
        HVSwitching: 
            - A1
            - B1
            - C1
         
        LVSwitching: 
            - 2!2!1
            - 2!4!2
        
     
    Idark: 
        HVSwitching: 
            - A1
            - B1
            - C2
         
        LVSwitching: 
     
    CV: 
        HVSwitching: 
            - A2
            - B2
            - C2
         
        LVSwitching: 
    
