"""Simply plots all data as curve plots"""

"""This script plots IVCV files together for files generated by QTC
Data must be """

import logging
import holoviews as hv

from forge.tools import customize_plot, holoplot, convert_to_df, config_layout
from forge.tools import twiny, relabelPlot
from forge.tools import plot_all_measurements, convert_to_EngUnits
from forge.specialPlots import dospecialPlots
from forge.utilities import line_intersection


class Curve_plots:
    def __init__(self, data, configs):

        self.log = logging.getLogger(__name__)
        self.data = convert_to_df(data, abs=False)
        self.config = configs
        self.df = []
        self.basePlots = None
        self.PlotDict = {"Name": "Curve_plots"}
        self.measurements = self.data["columns"]
        # hv.renderer('bokeh')

    def run(self):
        """Runs the script"""

        # Convert the units to the desired ones
        for meas in self.measurements:
            unit = (
                self.config.get("Curve_plots", {})
                .get(meas, {})
                .get("UnitConversion", None)
            )
            if unit:
                self.data = convert_to_EngUnits(self.data, meas, unit)

        # Plot all Measurements
        self.basePlots = plot_all_measurements(
            self.data,
            self.config,
            self.measurements[0],
            "Curve_plots",
            do_not_plot=[self.measurements[0]],
        )
        self.PlotDict["All"] = self.basePlots

        # Plot all special Plots:
        # Histogram Plot
        # self.Histogram = dospecialPlots(self.data, self.config, "Curve_plots",
        #                                "concatHistogram", self.measurements,
        #                                **self.config.get("Curve_plots", {}).get("AuxOptions", {}).get("concatHistogram", {}))
        # if self.Histogram:
        #    self.PlotDict["Histogram"] = self.Histogram
        #    self.PlotDict["All"] = self.PlotDict["All"] + self.Histogram

        # Whiskers Plot
        # self.WhiskerPlots = dospecialPlots(self.data, self.config, "Curve_plots", "BoxWhisker", self.measurements)
        # if self.WhiskerPlots:
        #    self.PlotDict["Whiskers"] = self.WhiskerPlots
        #   self.PlotDict["All"] = self.PlotDict["All"] + self.WhiskerPlots

        # Violin Plot
        # self.Violin = dospecialPlots(self.data, self.config, "Curve_plots", "Violin", self.measurements)
        # if self.Violin:
        #    self.PlotDict["Violin"] = self.Violin
        #   self.PlotDict["All"] = self.PlotDict["All"] + self.Violin

        # Reconfig the plots to be sure
        self.PlotDict["All"] = config_layout(
            self.PlotDict["All"], **self.config.get("Curve_plots", {}).get("Layout", {})
        )
        return self.PlotDict
