"""Simply plots all data as curve plots"""

"""This script plots IVCV files together for files generated by QTC
Data must be """

import logging
import holoviews as hv

hv.extension('bokeh')

from forge.tools import customize_plot, holoplot, convert_to_df, config_layout
from forge.tools import twiny, relabelPlot
from forge.tools import SimplePlot, convert_to_EngUnits
from forge.specialPlots import dospecialPlots
from forge.utilities import line_intersection


class TCAD:

    def __init__(self, data, configs):

        self.log = logging.getLogger(__name__)
        self.data = convert_to_df(data, abs=False)
        self.config = configs
        self.df = []
        self.basePlots = None
        self.analysisname = "TCAD"
        self.PlotDict = {"Name": self.analysisname}
        self.measurements = self.data["columns"]
        hv.renderer('bokeh')

        self.PlotLabels = [("IV_1", "IV", )]

    def run(self):
        """Runs the script"""

        # Convert the units to the desired ones
        for meas in self.measurements:
            unit = self.config[self.analysisname].get(meas, {}).get("UnitConversion", None)
            if unit:
                self.data = convert_to_EngUnits(self.data, meas, unit)

        # Plot all Measurements
        #self.basePlots = plot_all_measurements(self.data, self.config, self.measurements[0], self.analysisname, do_not_plot=[self.measurements[0]])
        #self.PlotDict["All"] = self.basePlots

        self.PlotDict["All"] = SimplePlot(self.data, self.config, "IV_1", "IV", self.analysisname)
        ["All"]["IV_1"] * 50259.5 * 677.3

        # Reconfig the plots to be sure
        self.PlotDict["All"] = config_layout(self.PlotDict["All"], **self.config.get(self.analysisname, {}).get("Layout", {}))
        return self.PlotDict
