--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    measurement_types: # Different measurement types which can be conducted
        - IV
        - CV


    # Optional parameters
    temp_history: 3600 # How much should be shown in the humidity history in seconds
    temphum_update_intervall: 5000 # Update intervall of the humidity controll in ms
    temphum_plugin: Brandbox_temperature_humidity
    time_format: "%H:%M:%S" # Time format of the humidity control
    GUI_update_interval: 200.0 # How often should the GUI be updated in ms

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered
        - EnvMonitor
       
