---
# This are the configurations for the logger
version: 1
disable_existing_logger: False
formatters:
  standard:
    format: '%(asctime)-15s - %(levelname)-10s - %(name)-40s - %(message)s'
  STDOut:
    format: '%(levelname)-10s - %(name)-40s - %(message)s'
handlers:
  # Define a default handler, you can add more if you need them
  default:
    level: INFO
    class: logging.StreamHandler
    formatter: STDOut
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: 'UniDAQ/Logfiles/QTC_Logfile.log'
    maxBytes: 10485760 # 10MB - 70 MB are about 2 Weeks of logs 
    backupCount: 5
    encoding: utf8
  errorHandler:
    class: UniDAQ.utilities.QueueEmitHandler # Self written handler for messages.
    level: ERROR
    #alternate: cfg://handlers.file # So it takes everything from this handler, others can be here as well
    queue: message_to_main # The queueobject it writes to, currently its a str not the object


loggers:
  # Define the behavior of a specific logger, in this case the utility, which then can be seperatly switched off.
  utilities:
    handlers: [default, file, errorHandler]
    level: INFO
    propagate: True

root:
  level: DEBUG # This is some kind of global minimum logging level
  handlers: [default, file, errorHandler]
