--- # Dummy config file for testing

  Filetype: CSV # Other options are json, ACII

  Analysis:
    - COVID19 # The type of analysis, which will be performed


# Optional Parameters

  # Options for the different Analyses scripts
  # These options are entirely up to you and what you need in your analysis
  COVID19:
      General: # Options common to all plots
          fontsize: {'title': 28, 'labels': 24, 'xticks': 15, 'yticks': 15, 'legend': 11}
          responsive: False
          width: 1800
          height: 800
          shared_axes: False
      Layout:
          cols: 1 # How many columns there are, these must the the names of the methods!!! and a valid parameter
      
      Normalize: False
      Countries:
          - Switzerland: 8292809
          - Italy: 62246674
          - Spain: 46660000
          - Austria: 8793370
          - Germany: 80457737
          - China: 1384688986
          - Iran: 83992949
          - France: 65273511
          - US: 329256465
          #- Belgium: 11589623
          #- "Korea, South": 51269185
          #- Mexico: 128932753
          
          
      GrowingRateMulti: 1000
          
      HistogramOptions:
          shared_axes: False
          alpha: 0.6

      confirmed:
          PlotLabel: "Confirmed Cases"
          PlotStyles:
            - Bars
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: True
              xrotation: 60
              #logy: True
              legend_position: top_left
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              shared_axes: False # If the axes should be shared with other plots, usually it is False
        
      recovered:
          PlotLabel: "Recovered Cases"
          PlotStyles:
            - Bars
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: True
              xrotation: 60
              legend_position: top_left
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              shared_axes: False # If the axes should be shared with other plots, usually it is False
             
      deaths:
          PlotLabel: "Deaths"
          PlotStyles:
            - Bars
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: True
              xrotation: 60
              legend_position: top_left
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              
      GvC:
           PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              show_grid: True
              xlabel: Total cases
              logx: True
              logy: True
              line_width: 4
              padding: !!python/tuple [5,1]
              #xlim: !!python/tuple [10,None]
              #ylim: !!python/tuple [1,None]
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
            