--- # Dummy config file for testing

  Filetype: ASCII # Other options are json

  #Output: ??? #Output basename of the plots

  #Save_as: # Possible options: html, (svg), png, pdf -> Only works if wkhtmltopdf is installed and html plot is generated,
    #- html
    #- png
    #- svg
    #- pdf # does not work correctly

  Analysis:
    - Curve_plots # The type of analysis, which will be performed

# Optional Parameters
  ASCII_file_specs: # The specifications for the ascii file type measurements files
    header_lines: 2
    measurement_description: 3
    units_line: 3
    data_start: 4
    data_separator: ";"

  # Options for the different Analyses scripts
  # These options are entirely up to you and what you need in your analysis
  Curve_plots:
      General: # Options common to all plots
          fontsize: {'title': 28, 'labels': 24, 'xticks': 24, 'yticks': 24, 'legend': 11}
          responsive: False
          width: 1200
          height: 700
          shared_axes: False
      Layout:
          cols: 1 # How many columns there are, these must the the names of the methods!!! and a valid parameter
      DoSpecialPlots: # Whether or not to do the SpecialPlot, it may not succeed if not at least one measuremnt has this special plot stated
          - concatHistogram
          - BoxWhisker
          
      AuxOptions: # All options which YOU want to have in your analysis. Unless you do something with them they do nothing
        concatHistogram:
            bins: 50
            #iqr: 0.1
      Cp1:
          PlotLabel: KIT C1 capacitor
          PlotStyles: # Here you can state some plot types you want to have, possible Options are Curve, Spike, Histogram, if non is stated, curve is selected
              - Scatter
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - concatHistogram
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              padding: !!python/tuple [0, 0.1]
              xformatter: "%.0f"
              yformatter: "%.2f"
              show_grid: True
              size: 5
             
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      Cp2:
          PlotLabel: KIT C2 capacitor
          PlotStyles: # Here you can state some plot types you want to have, possible Options are Curve, Spike, Histogram, if non is stated, curve is selected
              - Scatter
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - concatHistogram
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              padding: !!python/tuple [0, 0.1]
              xformatter: "%.0f"
              yformatter: "%.2f"
              show_grid: True
              size: 5
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      R1:
          PlotLabel: KIT R1 resistor
          PlotStyles: # Here you can state some plot types you want to have, possible Options are Curve, Spike, Histogram, if non is stated, curve is selected
              - Scatter
          UnitConversion: mega # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - concatHistogram
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              padding: !!python/tuple [0, 0.1]
              xformatter: "%.0f"
              yformatter: "%.2f"
              show_grid: True
              size: 5
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      R2:
          PlotLabel: KIT R2 resistor
          PlotStyles: # Here you can state some plot types you want to have, possible Options are Curve, Spike, Histogram, if non is stated, curve is selected
              - Scatter
          UnitConversion: giga # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - concatHistogram
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              padding: !!python/tuple [0, 0.1]
              xformatter: "%.0f"
              yformatter: "%.2f"
              show_grid: True
              size: 5
              gridstyle:
                  grid_line_color: black
                  grid_line_width: 1.5
                  minor_xgrid_line_color: lightgray
                  minor_ygrid_line_color: lightgray
                  xgrid_line_dash: [4, 4]
                  ygrid_line_dash: [10, 4]
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation