--- # Dummy config file for testing

# Optional Parameters
  ASCII_file_specs: # The specifications for the ascii file type measurements files
    header_lines: 9
    measurement_description: 10
    units_line: 11
    data_start: 12
    units:
        - A
        - A
        - F
        - F
        - A
        - A 
        - A 
        - A
        - F                       
        - Ohm                     
        - Ohm                     
        - F                       
        - F
        
  Analysis:
    - SQC_SELFTEST # The type of analysis, which will be performed
    
  Files:
    - "C:\\Users\\domin\\PycharmProjects\\COMET\\COMET\\config\\Setup_configs\\DataVisualization\\Plotting\\QTC_SELFTEST_newDecoupleWithDischarge.txt"

  abs_value_only: False
# Optional Parameters

  # Options for the different Analyses scripts
  # These options are entirely up to you and what you need in your analysis
  SQC_SELFTEST:
      General: # Options common to all plots
          fontsize: {'title': 28, 'labels': 24, 'xticks': 24, 'yticks': 24, 'legend': 11}
          responsive: False
          width: 1200
          height: 800
          shared_axes: False
          padding: !!python/tuple [0.1, 0.1]
          show_grid: True
          gridstyle:
              grid_line_color: black
              grid_line_width: 1.5
              minor_xgrid_line_color: lightgray
              minor_ygrid_line_color: lightgray
              xgrid_line_dash: [4, 4]
              ygrid_line_dash: [10, 4]
      Layout:
          cols: 1 # How many columns there are, these must the the names of the methods!!! and a valid parameter

      AuxOptions:
          singleHistogram:
              bins: 50
              iqr: 0.9
              commas: 9

      DoSpecialPlots: # Whether or not to do the SpecialPlot, it may not succeed if not at least one measurements has this special plot stated
          #- BoxWhisker
          - Histogram

      HistogramOptions:
          shared_axes: False
        
      BoxWhiskerOptions:
          shared_axes: False
          box_alpha: 0.3
          width: 1200
          height: 900

      Chuckleakage:
          PlotLabel: Cuck-leakage currents path
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - Histogram
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: current (pA) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      Istripempty:
          PlotLabel: Istrip currents path
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - Histogram
              - BoxWhisker
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: current (pA) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      Cacempty:
          PlotLabel: Coupling capacitance path
          UnitConversion: femto # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: capacitance (fF) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      Cintempty:
          PlotLabel: Interstrip Capacitance path
          UnitConversion: femto # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: capacitance (fF) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      Rpolyempty:
          PlotLabel: Bias resistor path
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: current (pA) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True # If you want to plot the y axis in engineering representation
      Rintempty:
          PlotLabel: Rint path
          UnitConversion: femto # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: current (fA) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True
      Idielempty:
          PlotLabel: Idiel path
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: current (fA) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True
      CVempty:
          PlotLabel: CV path
          UnitConversion: femto # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: capacitance (fF) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.0f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True
      R1:
          PlotLabel: KIT R1 - Rpoly resistor
          UnitConversion: mega # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: resistance (MOhm) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.4f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True
      R2:
          PlotLabel: KIT R2 - Rint resistor
          UnitConversion: giga # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: resistance (GOhm) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.3f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True
      C2:
          PlotLabel: KIT C2 - Cint capacitor
          UnitConversion: femto # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: capacitance (fF) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.2f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True
      C1:
          PlotLabel: KIT C1 - Cac capacitor
          UnitConversion: pico # Converts the units to nano (Warning: The correct units your data is in must be extractable from the measurement file!)
          AdditionalPlots:
              - BoxWhisker
              - Histogram
          PlotOptions: # These options will directly be passed to the renderer, make sure they are valid. Look into holoviews, what options are supported
              xlabel: measurement (#)
              ylabel: capacitance (pF) # This overrides the automatic generated ylabel
              shared_axes: False # If the axes should be shared with other plots, usually it is False
              xformatter: "%.0f"
              yformatter: "%.2f"
          ToolsOptions: # These options are for the PlotScripts tool box, or for the self written customizations
              yaxisENG: True