--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name
    
    
    GUI_render_order:
        - DeviceCommunication
        - Resources
        - DataBrowser
        
    Devices: # Name of the config entry
      2470SMU: # Some descriptor for the device
        Device_name: 2470 Keithley SMU  # Name of the device, this must be the same name as of one in the device library                                                                # The actual device name from which it should get all commands
        Device_IDN: KEITHLEY INSTRUMENTS,MODEL 2470,04424944,1.6.8d
        Connection_type: IP:TCPIP0::192.168.130.131::inst0::INSTR
        
        
    