--- # Block of dict entries

    # Critical parameters
    Settings_name: Defaults # The name of the settings which will be shown in the framework and will be the addressing name
    Operator: # The operators working on this machine
      - Dominic
      - Viktoria
      - Thomas
      - Marco

    Projects: # The project names of your sensor batches etc. musst be conform with the sensors entries
        - IFX 6 inch
        - HPK 6 inch
        - IFX 8 inch

    Sensor_types: # Different sensor types in the various projects
        IFX 6 inch:
            - Baby
            - PSs
            - Irrad35
            - Irrad25
            - PSs_Baby

        HPK 6 inch:
            - Irradiation

        IFX 8 inch:
            - SensorCenterBiasContact
            - SensorBaby
            - SensorIrradiation
            - Sensor2S

    measurement_types: # Different measurement types which can be conducted
        - IV
        - CV
        - Stripscan
        - IV_longterm
        - temperature
        - humidity
        - Cback
        - Cint
        - CintAC
        - Rint
        - Rpoly
        - Istrip
        - Idiel
        - Cac
        - Cback_scan
        - Cint_scan
        - Cac_scan
        - Idark
        - Rint_scan
        - waitingtime_scan

    measurement_order:
        - test_mode
        - IVCV
        - stripscan
        - singlestrip
        - dynamicwaiting

    # Optional parameters
    Thomas_mode: false # Shows white plots instead of black plots, because Thomas does not like black plots
    temp_history: 3600 # How much should be shown in the humidity history in seconds
    temphum_update_intervall: 5000 # Update intervall of the humidity controll in ms
    time_format: "%H:%M:%S" # Time format of the humidity control
    Test_mode: false # You dont want this
    GUI_update_interval: 200.0 # How often should the GUI be updated in ms
    elrange: 200e-9 # A predefined value for the elrange

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered
        - Main
        - Settings
        - Stripscan
        - StripAnalysis
        - Switching
        - DataBrowser
        - Resources
        - Alignment
        - Singlestrip
        - DynamicWaiting
        - Info

    # Devices aliases for internal use, the key will then be the frameworks internal representation and the value is the display name
    Aliases:
        temphum_controller: Brand Box
        Elmeter: ELMETER
        Switching: Matrix
        IVSMU: Bias_SMU
        Table_control: Corvus
        humidity_sensors: hum_sensors
        Air: pressure_air
        LCR: LCR
        2410SMU: SMU2
    lights_controller: Brand Box