--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    Operator: # The operators working on this machine
      - Dominic
      - Viktoria
      - Thomas
      - Marko

    measurement_types: # Different measurement types which can be conducted
        - IV
        - CV

    measurement_order: # aka. all measurement plugins
        - IVCV


    # Optional parameters
    temp_history: 3600 # How much should be shown in the humidity history in seconds
    temphum_update_intervall: 5000 # Update intervall of the humidity controll in ms
    #temphum_plugin: Brandbox_temperature_humidity
    time_format: "%H:%M:%S" # Time format of the humidity control
    Test_mode: false # You dont want this
    GUI_update_interval: 200.0 # How often should the GUI be updated in ms

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered

        - QTCMain
        #- Settings
        - Resources
        - DynamicWaiting

    Devices:
        237Keithley: # This is the name at which the device will be called. You can define an alias name as well in the aliases section
            Device_name: 237 Keithley SMU                                                                   # The actual device name from which it should get all commands
            Device_IDN: 237A10 
            Connection_type: GPIB:18
        
        Corvus:
            Device_name: ITK Corvus 
            Device_IDN: Corvus 1 462 1 0 
            Connection_type: RS232:17 
            Baud_rate: 9600
            
