---
    Device_name: 2410 Keithley SMU 2 depricated
    Device_type: SMU

    get_read: READ? 
    
    reset:
        - voltage_mode: FIXED 
        - default_reading_count: 1 
        - measurement_speed: 1 
        - complience: 100E-6 
        - beep: OFF
        - voltage_range: 1000 
        - range: 10E-6 
        - output: OFF
        - terminal: REAR 
        - reading_mode: CURR 
        - voltage: 0 
   
    set_output: OUTP  
    set_voltage_mode: SOUR:VOLT:MODE 
    set_reset_measure: ":SENS:FUNC:OFF: 'VOLT'"
    set_reading_mode: FORM:ELEM  
    set_reading_count: TRIG:COUN  
    set_measure_voltage: "SENS:FUNC 'VOLT'" 
    set_measurement_speed: SENS:RES:NPLC  
    set_beep: SYST:BEEP:STAT 
    set_complience: SENS:CURR:PROT  
    set_terminal: ROUT:TERM 
    set_voltage: SOUR:VOLT:LEV 
    set_current_range: SENS:CURR:RANG 
    set_source_voltage: SOUR:FUNC VOLT
    set_voltage_range: SOUR:VOLT:RANG
    set_source_current: SOUR:FUNC CURR 
    set_measure_current: "SENS:FUNC 'CURR'"   
