--- # Commands for venus-2 will work mostly with venus-1 as well but not 100%

    Device_name: ITK Corvus
    Device_type: Motor control 

    set_umotgrad: "{} setumotgrad"
    set_acceleration: "{} setaccel"
    set_units: "{} setunit"
    set_mode: "{} mode"
    set_axis_scale: "{} scale"
    set_axis: "{} setaxis"
    set_joy_speed: "{} setjoyspeed"
    set_umotmin: "{} setumotmin"
    set_speed: "{} setvel"
    set_pitch: "{} setpitch"
    set_joystick: "{} joystick"
    set_move_to: "{} {} {} move"
    set_motiondir: "{} setmotiondir"
    set_relative_move_to: "{} {} {} rmove"
    set_joysticktype: "{} setjoysticktype"
    set_polepairs: "{} setpolepairs"
    set_dimension: "{} setdim"

    get_error: geterror 
    get_pos_from_init: devpos 
    get_speed: getvel 
    get_acceleration: getaccel
    get_all_done: status 
    get_axis: getaxis 
    get_position: pos  

    table_zmin: 0.0 
    table_zmax: 20000.
    table_xmin: 0.0 
    table_xmax: 193260.
    table_ymin: 0.0 
    table_ymax: 97551.
    abort_movement: Ctrl C
    calibrate_motor: 
        - calibrate 
        - rm  
    command_order: -1 
    current_speed: 10000.0 
    device_IDN_query: identify 
    selftest: selftest 
    separator: " "
    reset_device: [restore, ico, clear]
    default_speed: 10000.0
    default_joy_speed: 10000.0

    reset: # Warning list values will be send seriel with the command!!! List of list will respect format string of command!!
        
        - units: [1 1, 1 2, 1 3, 1 0]
        - umotmin: [1850 1, 1850 2, 1850 3]
        - joy_speed: 10000.0
        - mode: 0
        - polepairs: [50 1, 50 2, 50 3]
        - joysticktype: 3
        - acceleration: 3000.0
        - pitch: [1.0 1, 1.0 2, 1.0 3, 1.0 0]
        - dimension: 3
        - speed: 10000.0
        - motiondir: [1 1, 1 2, 0 3]
        - joystick: 0
        - axis_scale: 1.0 1.0 1.0
        - umotgrad: [55 1, 55 2, 55 3]
        - axis: [1 1, 1 2, 1 3]
        - speed: 10000.0




