--- # Block of dict entries
    Device_name: 2410 Keithley SMU

    # All set parameters
    set_source_current: SOUR:FUNC CURR
    set_current_range: SENS:CURR:RANG {}
    set_measure_current: "SENS:FUNC 'CURR'"
    set_measure_voltage: "SENS:FUNC 'VOLT'"
    set_measure: "SENS:FUNC '{}'"
    set_measure_resistance: "SENS:FUNC 'RES'"
    set_source_voltage: SOUR:FUNC VOLT
    set_source_function: :SOUR:FUNC {}
    set_voltage_range: SOUR:VOLT:RANG {}
    set_measurement_speed: SENS:RES:NPLC  {}
    set_beep: SYST:BEEP:STAT {}
    set_reading_mode: FORM:ELEM  {}
    set_reading_count: TRIG:COUN  {}
    set_output: OUTP {}
    set_voltage_mode: SOUR:VOLT:MODE {}
    set_reset_measure_voltage: ":SENS:FUNC:OFF: 'VOLT'"
    set_reset_measure_current: ":SENS:FUNC:OFF: 'CURR'"
    set_compliance: SENS:CURR:PROT {}
    set_compliance_current: SENS:CURR:PROT {}
    set_compliance_voltage: :SENS:VOLT:PROT {}
    set_terminal: ROUT:TERM {}
    set_voltage: SOUR:VOLT:LEV {}
    set_meas_resistance: "SENS:FUNC 'RES'"
    set_resistance_range: ":SENS:RES:RANG: {}"
    set_resistance_mode: :SENS:RES:MODE {} # MANUAL; AUTO
    set_resitance_state: :SYST:RSEN {} # OFF=2wire, ON= 4wire

    # All get parameters
    get_read: READ?
    get_error: STAT:QUE:NEXT?

    # All reset device parameters
    reset:
        - resistance_mode: MANUAL
        - voltage_range: 20
        - source_function: VOLT
        - compliance_voltage: 1000
        #- current_range: AUTO
        - measure: CURR
        - reading_mode: CURR
        - voltage: 0
        - output: "OFF"
        - voltage_mode: FIXED
        - reading_count: 1
        - terminal: REAR
        - measurement_speed: 1
        - compliance: 100E-6
        - beep: "OFF"

    # Misc parameters
    Flow_control: "ON"
    Device_type: SMU
