--- # Block of dict entries
    Device_name: 2410 Keithley SMU

    # All set parameters
    set_source_current: SOUR:FUNC CURR {}
    set_current_range: SENS:CURR:RANG {}
    set_measure_current: SENS:FUNC 'CURR'
    set_measure_voltage: SENS:FUNC 'VOLT'
    set_source_voltage: SOUR:FUNC VOLT {}
    set_voltage_range: SOUR:VOLT:RANG {}
    set_measurement_speed: SENS:RES:NPLC  {}
    set_beep: SYST:BEEP:STAT {}
    set_reading_mode: FORM:ELEM  {}
    set_reading_count: TRIG:COUN  {}
    set_output: OUTP {}
    set_voltage_mode: SOUR:VOLT:MODE {}
    set_reset_measure_voltage: ":SENS:FUNC:OFF: 'VOLT'"
    set_reset_measure_current: ":SENS:FUNC:OFF: 'CURR'"
    set_compliance: SENS:CURR:PROT {}
    set_compliance_current: SENS:CURR:PROT {}
    set_terminal: ROUT:TERM {}
    set_voltage: SOUR:VOLT:LEV {}

    # All get parameters
    get_read: READ? 

    # All reset device parameters
    reset:
        - output: "OFF"
        - voltage: 0 
        - voltage_mode: FIXED 
        - reading_count: 1 
        - current_range: 10E-6 
        - terminal: REAR 
        - voltage_range: 1000  
        - reading_mode: CURR 
        - measurement_speed: 1 
        - compliance: 100E-6
        - beep: "OFF" 

    # Misc parameters
    Flow_control: "ON" 
    Device_type: SMU 



