--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)
    Operator: # The operators working on this machine
      - Dominic
      - Viktoria
      - Thomas
      - Marco

    measurement_types: # Different measurement types which can be conducted
        - IV
        - CV
        - Stripscan
        - IV_longterm
        - temperature
        - humidity
        - Cback
        - Cint
        - CintAC
        - Rint
        - Rpoly
        - Istrip
        - Idiel
        - Cac
        - Cback_scan
        - Cint_scan
        - Cac_scan
        - Idark
        - Rint_scan
        - waitingtime_scan

    measurement_order: # aka. all measurement plugins
        - IVCV
        - stripscan
        - frequencyscan
        - dynamicwaiting


    # Optional parameters
    Thomas_mode: false # Shows white plots instead of black plots, because Thomas does not like black plots
    temp_history: 3600 # How much should be shown in the humidity history in seconds
    temphum_update_intervall: 5000 # Update intervall of the humidity controll in ms
    temphum_plugin: Brandbox_temperature_humidity
    time_format: "%H:%M:%S" # Time format of the humidity control
    Test_mode: false # You dont want this
    GUI_update_interval: 200.0 # How often should the GUI be updated in ms
    elrange: 200e-9 # A predefined value for the elrange

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered

        - QTCMain
        - Settings
        - Stripscan
        - StripAnalysis
        - Switching
        - DataBrowser
        - Resources
        - Alignment
        - Singlestrip
        - DynamicWaiting


    # Devices aliases for internal use, the key will then be the frameworks internal representation and the value is the display name
    Aliases:
        temphum_controller: BrandBox
        #Elmeter: ELMETER
        Switching: Matrix
        BiasSMU: 2657 Keithley SMU
        Table_control: Corvus
        #humidity_sensors: hum_sensors
        #Air: pressure_air
        #LCR: LCR
        lights_controller: BrandBox

    Devices:
        2410SMU: # This is the name at which the device will be called. You can define an alias name as well in the aliases section
            Device_name: 2410 Keithley SMU                                                                  # The actual device name from which it should get all commands
            Device_IDN: KEITHLEY INSTRUMENTS INC.,MODEL 2410,0854671,C33   Mar 31 2015 09:32:39/A02  /J/H
            Connection_type: GPIB:16
            
        25657SMU:
            Device_name: 2657 Keithley SMU
            Connection_type: GPIB:26
            Device_IDN: Keithley Instruments Inc., Model 2657A 4356871, 1.1.5

        BrandBox:
            Device_name: BrandBox
            Connection_type: RS232:15
            Device_IDN: HV-Relay Controller V1.5/09.Oct.2018

            
        