{
  "Device_name": "2657 Keithley SMU",
  "Display_name": "Bias_SMU",
  "Device_type": "SMU",
  "Connection_type": "GPIB:26",
  "Device_IDN": "Keithley Instruments Inc., Model 2657A, 4356871, 1.1.5",
  "syntax": "",
  "separator": ",",
  "set_enable_beeper": "beeper.enable =",
  "default_enable_beeper": "beeper.ON",
  "set_beep": "beeper.beep",
  "CSV_beep": "time, frequency",
  "set_delay": "delay",
  "clear_display": "display.clear()",
  "get_annuciators": "print(display.getannuciators())",
  "set_lock_SMU": "display.locallockout =",
  "default_lock_SMU": "display.LOCK",
  "set_display_measurement": "display.screen =",
  "default_display_measurement": "display.SMUA",
  "set_display_text": "display.settext",
  "CSV_display_text": "text",
  "display_clear": "display.clear()",
  "display_dcamps": "display.smua.measure.func = display.MEASURE_DCAMPS",
  "display_dcvolts": "display.smua.measure.func = display.MEASURE_DCVOLTS",
  "display_dcohms": "display.smua.measure.func = display.MEASURE_DCOHMS",
  "display_dcwatts": "display.smua.measure.func = display.MEASURE_DCWATTS",
  "set_display_func": "display.smua.measure.func =",
  "default_display_func": "display.MEASURE_DCAMPS",
  "clear_errors": "errorqueue.clear()",
  "get_error_count": "print(errorqueue.count)",
  "get_next_error": "errorcode, message, severity = errorqueue.next() \n print(errorcode, message, severity)",
  "imp:default_queueclear": "dataqueue.clear()",
  "exit_script": "exit()",
  "initialize_lan": "lan.applysettings()",
  "set_lan_autoconnect": "lan.autoconnect =",
  "default_lan_autoconnect": "lan.ENABLE",
  "set_DNS": "lan.config.dns.address[1] = '0.0.0.0'",
  "set_domain": "lan.config.dns.domain = '0.0.0.0'",
  "set_hostname": "lan.config.dns.hostname = '2657KeithleySMU'",
  "set_verify_host": "lan.config.dns.verify =",
  "default_verify_host": "lan.ENABLE",
  "set_gateway": "lan.config.gateway =",
  "default_gateway": "'192.168.0.1'",
  "set_ipaddress": "lan.config.ipaddress =",
  "default_ipaddress": "'192.168.0.100'",
  "set_lan_config": "lan.config.method =",
  "default_lan_config":  "lan.MANUAL",
  "reset_lan_interface": "lan.reset()",
  "device_IDN_query": "*IDN?",
  "reset_device": ["*rst"],
  "abort": "smua.abort()",
  "store_calibration": "sma.cal.save()",
  "calibrate_highsense": "smuX.contact.calibratehi()",
  "calibrate_lo": "smuX.contact.calibratelo()",
  "set_autorange_current": "smua.measure.autorangei =",
  "default_autorange_current": "1",
  "set_autorange_voltage": "smua.measure.autorangev =",
  "default_autorange_voltage": "1",
  "set_autozero": "smua.measure.autozero =",
  "default_autozero": "smua.AUTOZERO_AUTO",
  "set_measurement_count": "smua.measure.count =",
  "default_measurement_count": "1",
  "set_filter_count": "smua.measure.filter.count =",
  "default_filter_count": "1",
  "set_filter_enable": "smua.measure.filter.enable =",
  "default_filter_enable": "smua.FILTER_ON",
  "set_filter": "smua.measure.filter.type =",
  "default_filter": "smua.FILTER_REPEAT_AVG",
  "set_current_range_low": "smua.measure.lowrangei = ",
  "set_voltage_range_low": "smua.measure.lowrangev = ",
  "default_voltage_range_low": "1",
  "default_current_range_low": "100e-12",
  "set_NPLC": "smua.measure.nplc = ",
  "default_NPLC": "1",
  "Read_voltage": "print(smua.measure.v())",
  "Read_current": "print(smua.measure.i())",
  "Read_iv": "print(smua.measure.iv())",
  "Read": "print(smua.measure.i())", 
  "set_source_current_autorange": "smua.source.autorangei = ",
  "set_source_voltage_autorange": "smua.source.autorangev = ",
  "default_source_current_autorange": "smua.AUTORANGE_ON",
  "default_source_voltage_autorange": "smua.AUTORANGE_ON",
  "set_source_func": "smua.source.func =",
  "default_source_func": "smua.OUTPUT_DCVOLTS",
  "set_voltage": "smua.source.levelv = ",
  "set_source_level_volts": "smua.source.levelv = ",
  "default_source_level_volts": "0",
  "set_complience_current": "smua.source.limiti = ",
  "default_complience_current": "50e-6",
  "set_complience": "smua.source.limiti = ",
  "set_complience_voltage": "smua.source.limitv = ",
  "default_complience_voltage": "1000",
  "set_offvoltage": "smua.source.offfunc =",
  "default_offvoltage": "smua.OUTPUT_DCVOLTS",
  "set_offcomplience": "smua.source.offlimiti = ",
  "default_offcomplience": "50e-6",
  "set_output": "smua.source.output = ",
  "default_output": "smua.OUTPUT_OFF",
  "set_current_range": "smua.measure.rangei = ",
  "set_measurement_delay": "smua.measure.delay = ",
  "default_measurement_delay": "smua.DELAY_AUTO",
  "set_measurement_delay_factor": "smua.measure.delayfactor =",
  "default_measurement_delay_factor": "1.0"

}