# This file includes all volatile variables and framework variables which are needed for the QTC setup to work
--- # Block of dict entries
  Settings_name: framework_variables
  End_time: NaN
  Start_time: NaN
  Bad_strips: 0
  Measurement_running: False
  Environment_status: False
  external_lights: False
  internal_lights: False
  chuck_temperature: 0
  humidity_control: False
  current_tempmin: 20
  current_tempmax: 25
  current_hummin: 20
  current_hummax: 25
  Table_state: True
  current_selected_browser_value: None
  current_selected_main_object: None
  Current_sensor: None
  Current_operator: None
  Current_filename: None
  Current_project: None
  update_counter: 0
  last_plot_update: 0
  current_led_state: None
  new_data: True
  IV_measure: [True, -10.0,-60.0, 12]  #do_it min voltage compliance steps
  CV_measure: [True, -10.0, -50.0, 10]  # do_itmin voltage compliance steps
  Stripscan_measure: [True, -10.0, -50.0, 10]  #do_itmin voltage compliance steps
  Idiel_measure: [True, 1, 1, 200]  # do_it every start stop
  Rpoly_measure: [True, 1, 1, 200]  # do_it every start stop
  Cac_measure: [True, 1, 1, 200]  # do_it every start stop
  Idark_measure: [True, 1, 1, 200]  # do_it every start stop
  Rint_measure: [True, 1, 1, 200]  # do_it every start stop
  Cint_measure: [True, 1, 1, 200]  # do_it every start stop
  Cback_measure: [False, 1, 1, 200]  # do_it every start stop
  Istrip_measure: [True, 1, 1, 200]  # do_it every start stop
  IV_longterm_measure: [False, -10, -60.0, 5]  # do_it min voltage compliance steps
  IVCV_refinement: [True, 0, -50, 2] # do_refinement, min, max, step
  CintAC_measure: [False, 1, 1, 200]
  Table_stay_down: False
  height_movement: 800 # height movement of the table when moving the table in um
  table_ready: False
  bias_voltage: 0
  current_switching: {}
  joystick: False
  zlock:    True
  table_is_moving: False
  V0: None
  current_strip: -1
  strip_scan_time: 10
  IVCV_time: 300
  Rint_MinMax: [-1.,1.,0.1]

              