--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    Operator: # The operators working on this machine
      - Dominic
      - Viktoria
      - Thomas
      - Marco

    measurement_types: # Different measurement types which can be conducted
        - IV
        - CV
        - dynamicwaiting

    measurement_order: # aka. all measurement plugins
        - IVCV
        - dynamicwaiting


    # Optional parameters
    temp_history: 3600 # How much should be shown in the humidity history in seconds
    temphum_update_intervall: 5000 # Update intervall of the humidity controll in ms
    temphum_plugin: Brandbox_temperature_humidity
    time_format: "%H:%M:%S" # Time format of the humidity control
    Test_mode: false # You dont want this
    GUI_update_interval: 200.0 # How often should the GUI be updated in ms

    GUI_render_order: # Give a render order if need be, otherwise all found gui elements will be rendered
        - P3Main
        - DynamicWaiting
        - DeviceCommunication
        - DataBrowser
        - Resources

      # Devices aliases for internal use, the key will then be the frameworks internal representation and the value is the display name
    Aliases:
      temphum_controller: BrandBox
      BiasSMU: 2470 Keithley SMU
      lights_controller: BrandBox

    Devices:
      2470SMU:
        Device_name: 2470 Keithley SMU                                                                  # The actual device name from which it should get all commands
        Device_IDN: KEITHLEY INSTRUMENTS,MODEL 2470,04424944,1.6.8d
        Connection_type: IP:TCPIP0::192.168.130.131::inst0::INSTR


    Measurement_configs: # These are optional values. Here you can change the standard configs for e.g. IVCV measurement
                         # For all possible parameters see e.g. the IVCV measurement plugin. under xxx_configs in the init
      IVCV:
        # Devices Configs
        BiasSMU: BiasSMU
        LCRMeter: Agilent E4980A
        DischargeSMU: None
        Switching: None

        # How to read from the device
        GetReadSMU: get_read # This read can be a single current read or current, voltage pair
        GetReadLCR: get_read

        # General Configs for the measurements
        Meas_order: interlaced # Options: interlaced or sequential
        BaseConfig: []
        IVConfig:
          - [set_terminal, smu.TERMINALS_REAR]
        CVConfig: []
            
