--- # Block of dict entries

    # Critical parameters
    Settings_name: settings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    TelegramBot:
        Dominic: 260848510
    Current_operator: Dominic

    433MHz_Transiever:
        path: "~/git_repos/433Utils/RPi_utils"
        Codes:
          Light1:
            - 001100 3
          Light2:
            - 001100 2
            - 001100 3

    # Optional parameters
    temp_history: 3600 # How much should be shown in the humidity history in seconds
    temphum_update_interval: 10000 # Update intervall of the humidity controll in ms
    temphum_plugin: OneWireEnv
    time_format: "%H:%M:%S" # Time format of the humidity control
    GUI_update_interval: 200.0 # How often should the GUI be updated in ms
    show_toolbar: False

    Socket_connection: # Config for the socket connection, for data transfer between processes
        Host:
          IP: 127.0.0.2
          Port: 65432

        Client:
          IP: 127.0.0.4
          Port: 65432

       
