IVCV:
  Do: true
  Measurements:
    CV:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 50
      Do: true
      End Voltage [V]:
      - -1000
      - 0
      - -10
      - -10
      Voltage Step [V]:
      - -100
      - 0
      - -10
      - -1
    IV:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 50
      Do: false
      End Voltage [V]:
      - -1000
      - 0
      - -5
      - -1000
      Voltage Step [V]:
      - -100
      - 0
      - -5
      - -5
    Voltage Steps Refinement:
      Do: false
      End Voltage[V]:
      - -1000
      - 0
      - -1000
      - -100
      Start Voltage[V]:
      - -1000
      - 0
      - 0
      - 0
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -1
  Units:
    CV:
    - capacitance
    - F
    IV:
    - current
    - A
    X-Axis:
    - voltage
    - V
Settings_name: CV
