Frequency Scan:
  Do: true
  Measurements:
    CV:
      Amplitude [mV]:
      - 0
      - 1000
      - 100
      - 100
      Do: false
      End Freq [Hz]:
      - 0
      - 2000000
      - 10000
      - 2000000
      Start Freq [Hz]:
      - 100
      - 2000000
      - 10000
      - 100
      Steps:
      - 0
      - 1000
      - 10
      - 10
    Cac:
      Amplitude [mV]:
      - 0
      - 1000
      - 100
      - 100
      Do: true
      End Freq [Hz]:
      - 0
      - 2000000
      - 10000
      - 2000000
      Start Freq [Hz]:
      - 100
      - 2000000
      - 10000
      - 100
      Steps:
      - 0
      - 1000
      - 10
      - 10
      Strip [#]:
      - 1
      - 2032
      - 1
      - 1
    Cint:
      Amplitude [mV]:
      - 0
      - 1000
      - 100
      - 100
      Do: false
      End Freq [Hz]:
      - 0
      - 2000000
      - 10000
      - 2000000
      Start Freq [Hz]:
      - 100
      - 2000000
      - 10000
      - 100
      Steps:
      - 0
      - 1000
      - 10
      - 10
      Strip [#]:
      - 1
      - 2032
      - 1
      - 1
    General:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 100
      Do: true
      End Voltage [V]:
      - -1000
      - 0
      - -10
      - -20
      Start Voltage [V]:
      - -1000
      - 0
      - -10
      - -10
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -10
IVCV:
  Do: false
  Measurements:
    CV:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 50
      Do: true
      End Voltage [V]:
      - -1000
      - 0
      - -10
      - -600
      Voltage Step [V]:
      - -100
      - 0
      - -10
      - -5
    IV:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 50
      Do: true
      End Voltage [V]:
      - -1000
      - 0
      - -5
      - -1000
      Voltage Step [V]:
      - -100
      - 0
      - -5
      - -5
    Voltage Steps Refinement:
      Do: true
      End Voltage[V]:
      - -1000
      - 0
      - -1000
      - -100
      Start Voltage[V]:
      - -1000
      - 0
      - 0
      - 0
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -1
  Units:
    CV:
    - capacitance
    - F
    IV:
    - current
    - A
    X-Axis:
    - voltage
    - V
Settings_name: FreqTest.yml
Stripscan:
  Do: true
  Measurements:
    Cac:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Cint:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    General:
      Bias Voltage [V]:
      - -1000
      - 0
      - -10
      - -600
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 100
      Do: true
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -10
    Idark:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Idiel:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Istrip:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Rint:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Rpoly:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
  Units:
    Cac:
    - capacitance
    - F
    Cint:
    - capacitance
    - F
    Idark:
    - current
    - A
    Idiel:
    - current
    - A
    Istrip:
    - current
    - A
    Rint:
    - resistance
    - Ohm
    Rpoly:
    - resistance
    - Ohm
    X-Axis:
    - Strip
    - '#'
