--- # Block of dict entries

    # Critical parameters
    Settings_name: IVCVSettings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)
    
    IVCV:
        Do: True
        Units: 
            X-Axis: [voltage, V]
            IV: [current, A]
            CV: [capacitance, F] 
        Measurements:
            IV:
                Do: True 
                End Voltage [V]: [-1000,0,-5, -1000] # Min/Max/SpinStep/Value
                Voltage Step [V]: [-100,-0,-5, -5] # Min/Max/SpinStep/Value
                Compliance [uA]: [0, 1000, 10, 50] # Min/Max/SpinStep/Value
            CV:
                Do: True
                End Voltage [V]: [-1000, -0, -10,-600] # Min/Max/SpinStep/Value
                Voltage Step [V]: [-100, 0, -10, -5] # Min/Max/SpinStep/Value
                Compliance [uA]: [0, 1000, 10, 50] # Min/Max/SpinStep/Value
            Voltage Steps Refinement:
                Do: True
                Start Voltage[V]: [-1000, 0, 0, 0] # Min/Max/SpinStep/Value
                End Voltage[V]: [-1000, -0, -1000, -100] # Min/Max/SpinStep/Value
                Voltage Step [V]: [-100, 0, -1, -1] # Min/Max/SpinStep/Value
    