--- # Block of dict entries

    # Critical parameters
    Settings_name: StripscanSettings # The name of the settings which will be shown in the framework and will be the addressing name (settings here is important)

    Stripscan:
        Do: True
        Units:
            X-Axis: [Strip, "#"]
            Istrip: [current, A]
            Idiel: [current, A]
            Idark: [current, A]
            Cac: [capacitance, F]
            Cint: [capacitance, F]
            Rpoly: [resistance, Ohm]
            Rint: [resistance, Ohm]
        Measurements:
            General:
                Do: True
                Bias Voltage [V]: [-1000, 0, -10,-600]
                Voltage Step [V]: [-100, 0, -1, -10]
                Compliance [uA]: [0,1000,10, 100] # Min/Max/SpinStep/Value
            Istrip:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
            Idiel:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
            Idark:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
            Cac:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
            Rpoly:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
            Rint:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
            Cint:
                Do: True
                Measure Every: [0,2032,1,1] # Min/Max/SpinStep/Value
                Start Strip: [0,2032,1,0] # Min/Max/SpinStep/Value
                End Strip: [0,2032,1,2032] # Min/Max/SpinStep/Value
