Frequency Scan:
  Do: false
  Measurements:
    Cac:
      Amplitude:
      - 0
      - 1
      - 0.1
      - 0.5
      Bias Voltage:
      - 0
      - -1000
      - 10
      - 300
      Do: true
      EndFreq:
      - 0
      - 1000000
      - 10000
      - 1000000
    Cint:
      Amplitude:
      - 0
      - 1
      - 0.1
      - 0.5
      Bias Voltage:
      - 0
      - -1000
      - 10
      - 300
      Do: true
      EndFreq:
      - 0
      - 1000000
      - 10000
      - 1000000
IVCV:
  Do: false
  Measurements:
    CV:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 100
      Do: true
      End Voltage [V]:
      - -1000
      - 0
      - -10
      - -600
      Voltage Step [V]:
      - -100
      - 0
      - -10
      - -10
    IV:
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 100
      Do: true
      End Voltage [V]:
      - -1000
      - 0
      - -5
      - -1000
      Voltage Step [V]:
      - -100
      - 0
      - -5
      - -10
    Voltage Steps Refinement:
      Do: true
      End Voltage[V]:
      - -1000
      - 0
      - -1000
      - -400
      Start Voltage[V]:
      - -1000
      - 0
      - 0
      - 0
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -5
  Units:
    CV:
    - capacitance
    - F
    CVQValue:
    - Q value
    - arb. units
    IV:
    - current
    - A
    Voltage:
    - Voltage
    - V
    X-Axis:
    - Voltage
    - V
Settings_name: Stripscan_PSs.yml
Stripscan:
  Do: true
  Measurements:
    Cac:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
    Cint:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 50
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
    General:
      Bias Voltage [V]:
      - -1000
      - 0
      - -10
      - -600
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 100
      Do: true
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -10
    Idark:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
    Idiel:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
    Istrip:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
    Rint:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 50
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
    Rpoly:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 1920
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 1
  Units:
    Cac:
    - capacitance
    - F
    Cint:
    - capacitance
    - F
    Idark:
    - current
    - A
    Idiel:
    - current
    - A
    Istrip:
    - current
    - A
    Rint:
    - resistance
    - Ohm
    Rint_scan:
    - current
    - A
    Rpoly:
    - resistance
    - Ohm
    Strip:
    - Stripposition
    - '#'
    X-Axis:
    - Strip
    - '#'
raw: "Frequency Scan:\n  Do: false\n  Measurements:\n    Cac:\n      Amplitude:\n\
  \      - 0\n      - 1\n      - 0.1\n      - 0.5\n      Bias Voltage:\n      - 0\n\
  \      - -1000\n      - 10\n      - 300\n      Do: true\n      EndFreq:\n      -\
  \ 0\n      - 1000000\n      - 10000\n      - 1000000\n    Cint:\n      Amplitude:\n\
  \      - 0\n      - 1\n      - 0.1\n      - 0.5\n      Bias Voltage:\n      - 0\n\
  \      - -1000\n      - 10\n      - 300\n      Do: true\n      EndFreq:\n      -\
  \ 0\n      - 1000000\n      - 10000\n      - 1000000\nIVCV:\n  Do: true\n  Measurements:\n\
  \    CV:\n      Compliance [uA]:\n      - 0\n      - 1000\n      - 10\n      - 100\n\
  \      Do: true\n      End Voltage [V]:\n      - -1000\n      - 0\n      - -10\n\
  \      - -600\n      Voltage Step [V]:\n      - -100\n      - 0\n      - -10\n \
  \     - -10\n    IV:\n      Compliance [uA]:\n      - 0\n      - 1000\n      - 10\n\
  \      - 100\n      Do: true\n      End Voltage [V]:\n      - -1000\n      - 0\n\
  \      - -5\n      - -1000\n      Voltage Step [V]:\n      - -100\n      - 0\n \
  \     - -5\n      - -10\n    Voltage Steps Refinement:\n      Do: true\n      End\
  \ Voltage[V]:\n      - -1000\n      - 0\n      - -1000\n      - -400\n      Start\
  \ Voltage[V]:\n      - -1000\n      - 0\n      - 0\n      - 0\n      Voltage Step\
  \ [V]:\n      - -100\n      - 0\n      - -1\n      - -5\n  Units:\n    CV:\n   \
  \ - capacitance\n    - F\n    CVQValue:\n    - Q value\n    - arb. units\n    IV:\n\
  \    - current\n    - A\n    Voltage:\n    - Voltage\n    - V\n    X-Axis:\n   \
  \ - Voltage\n    - V\nSettings_name: Stripscan_PSs.yml\nStripscan:\n  Do: false\n\
  \  Measurements:\n    Cac:\n      Do: true\n      End Strip:\n      - 0\n      -\
  \ 2032\n      - 1\n      - 1920\n      Measure Every:\n      - 0\n      - 2032\n\
  \      - 1\n      - 1\n      Start Strip:\n      - 0\n      - 2032\n      - 1\n\
  \      - 1070\n    Cint:\n      Do: true\n      End Strip:\n      - 0\n      - 2032\n\
  \      - 1\n      - 1920\n      Measure Every:\n      - 0\n      - 2032\n      -\
  \ 1\n      - 50\n      Start Strip:\n      - 0\n      - 2032\n      - 1\n      -\
  \ 1070\n    General:\n      Bias Voltage [V]:\n      - -1000\n      - 0\n      -\
  \ -10\n      - -600\n      Compliance [uA]:\n      - 0\n      - 1000\n      - 10\n\
  \      - 100\n      Do: true\n      Voltage Step [V]:\n      - -100\n      - 0\n\
  \      - -1\n      - -10\n    Idark:\n      Do: true\n      End Strip:\n      -\
  \ 0\n      - 2032\n      - 1\n      - 1920\n      Measure Every:\n      - 0\n  \
  \    - 2032\n      - 1\n      - 1\n      Start Strip:\n      - 0\n      - 2032\n\
  \      - 1\n      - 1070\n    Idiel:\n      Do: true\n      End Strip:\n      -\
  \ 0\n      - 2032\n      - 1\n      - 1920\n      Measure Every:\n      - 0\n  \
  \    - 2032\n      - 1\n      - 1\n      Start Strip:\n      - 0\n      - 2032\n\
  \      - 1\n      - 1070\n    Istrip:\n      Do: true\n      End Strip:\n      -\
  \ 0\n      - 2032\n      - 1\n      - 1920\n      Measure Every:\n      - 0\n  \
  \    - 2032\n      - 1\n      - 1\n      Start Strip:\n      - 0\n      - 2032\n\
  \      - 1\n      - 1070\n    Rint:\n      Do: true\n      End Strip:\n      - 0\n\
  \      - 2032\n      - 1\n      - 1920\n      Measure Every:\n      - 0\n      -\
  \ 2032\n      - 1\n      - 50\n      Start Strip:\n      - 0\n      - 2032\n   \
  \   - 1\n      - 1070\n    Rpoly:\n      Do: true\n      End Strip:\n      - 0\n\
  \      - 2032\n      - 1\n      - 1920\n      Measure Every:\n      - 0\n      -\
  \ 2032\n      - 1\n      - 1\n      Start Strip:\n      - 0\n      - 2032\n    \
  \  - 1\n      - 1070\n  Units:\n    Cac:\n    - capacitance\n    - F\n    Cint:\n\
  \    - capacitance\n    - F\n    Idark:\n    - current\n    - A\n    Idiel:\n  \
  \  - current\n    - A\n    Istrip:\n    - current\n    - A\n    Rint:\n    - resistance\n\
  \    - Ohm\n    Rint_scan:\n    - current\n    - A\n    Rpoly:\n    - resistance\n\
  \    - Ohm\n    Strip:\n    - Stripposition\n    - '#'\n    X-Axis:\n    - Strip\n\
  \    - '#'\n"
