Settings_name: TestStripscan.yml
Stripscan:
  Do: true
  Measurements:
    Cac:
      Do: false
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Cint:
      Do: false
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    General:
      Bias Voltage [V]:
      - -1000
      - 0
      - -10
      - -5
      Compliance [uA]:
      - 0
      - 1000
      - 10
      - 100
      Do: true
      Voltage Step [V]:
      - -100
      - 0
      - -1
      - -10
    Idark:
      Do: true
      End Strip:
      - 0
      - 2032
      - 1
      - 140
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 120
    Idiel:
      Do: false
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Istrip:
      Do: false
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Rint:
      Do: false
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
    Rpoly:
      Do: false
      End Strip:
      - 0
      - 2032
      - 1
      - 2032
      Measure Every:
      - 0
      - 2032
      - 1
      - 1
      Start Strip:
      - 0
      - 2032
      - 1
      - 0
  Units:
    Cac:
    - capacitance
    - F
    Cint:
    - capacitance
    - F
    Idark:
    - current
    - A
    Idiel:
    - current
    - A
    Istrip:
    - current
    - A
    Rint:
    - resistance
    - Ohm
    Rpoly:
    - resistance
    - Ohm
    X-Axis:
    - Strip
    - '#'
