---
  Settings_name: Badstrip # The name of the settings, which will be shown in the framework and will be the addressing name

  # General Settings
  author: Dominic Bloech
  author_email: dominic.bloech@oeaw.ac.at
  fit_cluster_size: 10 # How large should be the cluster size for fitting
  output_folder: C:\Users\dbloech\PycharmProjects\Doktorat\QTC-Software\UniDAQ\rubbish
  header_lines: 19 # How many header lines are there
  measurement_description: 20 # line where the different measurements are described
  units_line: 21 # Which line ist the units line
  data_start: 22
  quantile: 0.95 # Quantile for the lms_line fit from Rudi
  remove_outliner: True # Just for plotting important
  outlier_std: 3 # Excludes all values which are outlier compared to the std*n


  # General Parameters
  MeasStripvsTotal: 1.3 # The factor the sum of the strip current can have compared to the total Idark (median)

  ## AC and DC bad needle contact (if not otherwise written, all factors apply to the median of the respective parameter
  Istripfactor: 3 # Factor at which it is considered to be a low Istrip
  Rpolyfactor: 3 # Factor at which it is considered to be a high Rpoly
  Capfactor: 1.5 # Factor at which it is considered to be a out of bounds Cap
  maximumCapOutliner: 30 # Maximum number to look for non optimal/bad DC 1 and 2 needle contact in the Capacitance measurements

  ## Pinhole
  IdielThresholdCurrent: 0.5e-9 # Current at which we say it is charateristic for a pinhole

  ## LMS line fit
  LMSsize: 50 # Clustersize for the lms fit, warning cpu time increases with clustersize!!!

  ## Closeness parameters, is needed for comparisons between values and the lms fit (implant open etc.)
  ## Used equation: absolute(a - b) <= (atol + rtol * absolute(b))
  rtol: 0.3 # The relative tolerance parameter
  atol: 0 # The absolute tolerance parameter (not so important)

  # Threshold factors, factors are applied to the lms fit. So factor 0.5 means with LowCap that everything below 0.5 of the lms fit will be considered
  # Same holds for the high factors but the other way round.
  HighIstrip: 3
  HighRpoly: 2.5
  LowCap: 0.7


  # Pad parameter
  # Parameters {Name of measurement: [Nominal value, -[dmin, dmax], varianz in percent of mean}
  Rpoly:
    - 1500000
    - [1200000, 1800000]
    - 5

  Istrip:
    - -100e-12
    - [-200e-12,0]
    - 20

  Idiel:
    - 1e-12
    - [-0.5e-9,0.5e-9]
    - 20

  Idark:
    - 5e-6
    - [-500e-9, -150e-9]
    - 5.0

  Cint:
    - 0.7e-12
    - [0.3e-12, 5e-12]
    - 5

  Rint:
    - 100e9
    - [50e9, 1e12]
    - 50.0

  # AC pad parameters
  Cac:
    - 1.4e-10
    - [120e-12, 160e-12]
    - 5

  # Termperature
  Temperature:
    - 23
    - [20, 23]
    - 2

  # Humidity
  Humidity:
    - 22
    - [18, 27]
    - 10

  # Plot sections parameters
  do_plot: True # Should plots be done or not
  export_plot: True # Should the plots be exported, is False when do_plots = False
  export_results: True # Export analysis object for later import


